all:
  children:
    piholes:
      hosts:
        pihole-1:
          ansible_host: 192.168.1.228  # Update with your Pi's IP
          ansible_user: devops
          ansible_python_interpreter: /usr/bin/python3