all:
  children:
    dns_servers:
      children:
        piholes:
          hosts:
            pihole-1:
              ansible_host: 192.168.86.228
              ansible_user: devops
              ansible_python_interpreter: /usr/bin/python3
              ansible_become: yes
              ansible_become_method: sudo