---
- name: Generate Terraform Configurations
  hosts: localhost
  gather_facts: false
  vars:
    tf_output_dir: "../infrastructure/terraform"
    template_dir: "roles/tf_generator/templates"
  
  tasks:
    - name: Ensure Terraform directory exists
      win_file:
        path: "{{ tf_output_dir }}"
        state: directory

    - name: Generate main Terraform configuration
      win_template:
        src: "{{ template_dir }}/main.tf.j2"
        dest: "{{ tf_output_dir }}/main.tf"

    - name: Generate variables file
      win_template:
        src: "{{ template_dir }}/variables.tf.j2"
        dest: "{{ tf_output_dir }}/variables.tf"

    - name: Generate provider configuration
      win_template:
        src: "{{ template_dir }}/providers.tf.j2"
        dest: "{{ tf_output_dir }}/providers.tf"