---
- name: Apply common configuration to all hosts
  hosts: all
  roles:
    - common

- name: Configure Pi-hole servers
  hosts: piholes
  become: true
  tasks:
    - name: Include SELinux configuration
      ansible.builtin.include_tasks: roles/pi-hole/tasks/selinux.yml
      when: ansible_os_family == "RedHat"
    
    - name: Include Pi-hole role
      ansible.builtin.include_role:
        name: pi-hole